<?php defined('BASEPATH') OR exit('No direct script access allowed');

class Migration_Create_category_table extends CI_Migration {

    public function up()
    {
        // set default engine
        $this->db->query('SET storage_engine=MYISAM;');

        // Drop table 'category' if it exists		
        if ($this->db->table_exists('category'))
        {
            $this->dbforge->drop_table('category');
        }

        // Table structure for table 'category'
        $this->dbforge->add_field(array(
            'id' => array(
                'type' => 'INT',
                'constraint' => '11',
                'unsigned' => TRUE,
                'auto_increment' => TRUE
            ),
            'parent_id' => array(
                'type' => 'INT',
                'constraint' => '11',
                'unsigned' => TRUE
            ),
            'caption' => array(
                'type' => 'VARCHAR',
                'constraint' => '100',
            ),
            'slug' => array(
                'type' => 'VARCHAR',
                'constraint' => '100',
				'null' => TRUE
            ),
            'article' => array(
                'type' => 'TINYINT',
                'constraint' => 1,
                'default' => 0
            ),
            'market' => array(
                'type' => 'TINYINT',
                'constraint' => 1,
                'default' => 0
            ),
            'real_estate' => array(
                'type' => 'TINYINT',
                'constraint' => 1,
                'default' => 0
            ),
            'job' => array(
                'type' => 'TINYINT',
                'constraint' => 1,
                'default' => 0
            ), 
            'order' => array(
                'type'  => 'TINYINT',
                'constraint' => '6',
                'unsigned'  => TRUE,
                'default'   => 0,
            ),
            'status' => array(
                'type' => 'TINYINT',
                'constraint' => 1,
                'default' => 1
            ),
            'created_at' => array(
                'type'  => 'INT',
                'constraint' => '11'
            ),
            'updated_at'   => array(
               'type'  => 'INT',
                'constraint' => '11'
            )
        ));
        $this->dbforge->add_key('id', TRUE);
        $this->dbforge->create_table('category');
        
        // insert data
        $data = array(
            array(
                'id'    => 1,
                'caption' => 'ដំណាំ',
		'slug' => 'ដំណាំ',
                'parent_id' => 0,
                'article'  => 1,
                'market'  => 1,
		'real_estate' => 0,
		'job' => 0,
                'order' => 1,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 2,
                'caption' => 'សត្វ',
		'slug' => 'សត្វ',
                'parent_id' => 0,
                'article'  => 1,
                'market'  => 1,
		'real_estate' => 0,
		'job' => 0,
                'order' => 2,
                'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 3,
                'caption' => 'សម្ភារៈ និងកសិផល',
		'slug' => 'សម្ភារៈ-និងកសិផល',
                'parent_id' => 0,
                'article'  => 0,
                'market'  => 1,
		'real_estate' => 0,
		'job' => 0,
                'order' => 3,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 4,
                'caption' => 'ស្រែ​ ចំការ កសិដ្ឋាន',
		'slug' => 'ស្រែ​-ចំការ-កសិដ្ឋាន',
                'parent_id' => 0,
                'article'  => 0,
                'market'  => 0,
		'real_estate' => 1,
		'job' => 0,
                'order' => 4,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 5,
                'caption' => 'ការងារ',
		'slug' => 'ការងារ',
                'parent_id' => 0,
                'article'  => 0,
                'market'  => 0,
		'real_estate' => 0,
		'job' => 1,
                'order' => 5,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            // Crop
            array(
                'id'    => 6,
                'caption' => 'ស្រូវ និងអង្ករ',
		'slug' => 'ស្រូវ-និងអង្ករ',
                'parent_id' => 1,
                'article'  => 1,
                'market'  => 1,
		'real_estate' => 0,
		'job' => 0,
                'order' => 1,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 7,
                'caption' => 'ពោត',
		'slug' => 'ពោត',
                'parent_id' => 1,
                'article'  => 1,
                'market'  => 1,
		'real_estate' => 0,
		'job' => 0,
                'order' => 2,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 8,
                'caption' => 'បន្លែ',
		'slug' => 'បន្លែ',
                'parent_id' => 1,
                'article'  => 1,
                'market'  => 1,
		'real_estate' => 0,
		'job' => 0,
                'order' => 3,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 9,
                'caption' => 'ខ្ញី',
		'slug' => 'ខ្ញី',
                'parent_id' => 1,
                'article'  => 1,
                'market'  => 1,
		'real_estate' => 0,
		'job' => 0,
                'order' => 4,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 10,
                'caption' => 'ម្រេច',
		'slug' => 'ម្រេច',
                'parent_id' => 1,
                'article'  => 1,
                'market'  => 1,
		'real_estate' => 0,
		'job' => 0,
                'order' => 5,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 11,
                'caption' => 'កៅស៊ូ',
		'slug' => 'កៅស៊ូ',
                'parent_id' => 1,
                'article'  => 1,
                'market'  => 1,
		'real_estate' => 0,
		'job' => 0,
                'order' => 6,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 12,
                'caption' => 'ស្វាយចន្ទី',
		'slug' => 'ស្វាយចន្ទី',
                'parent_id' => 1,
		'article'  => 1,
                'market'  => 1,
		'real_estate' => 0,
		'job' => 0,
                'order' => 7,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 13,
                'caption' => 'ដំឡូងមី',
		'slug' => 'ដំឡូងមី',
                'parent_id' => 1,
		'article'  => 1,
                'market'  => 1,
		'real_estate' => 0,
		'job' => 0,
                'order' => 8,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array('id'    => 14,
                'caption' => 'សណ្តែកសៀង',
		'slug' => 'សណ្តែកសៀង',
                'parent_id' => 1,
		'article'  => 1,
                'market'  => 1,
		'real_estate' => 0,
		'job' => 0,
                'order' => 9,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 15,
                'caption' => 'អំពៅ',
		'slug' => 'អំពៅ',
                'parent_id' => 1,
		'article'  => 1,
                'market'  => 1,
		'real_estate' => 0,
		'job' => 0,
                'order' => 10,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            // Animal
            array(
                'id'    => 16,
                'caption' => 'សត្វគោ',
		'slug' => 'សត្វគោ',
                'parent_id' => 2,
		'article'  => 1,
                'market'  => 1,
		'real_estate' => 0,
		'job' => 0,
                'order' => 1,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 17,
                'caption' => 'សត្វជ្រូក',
		'slug' => 'សត្វជ្រូក',
                'parent_id' => 2,
		'article'  => 1,
                'market'  => 1,
		'real_estate' => 0,
		'job' => 0,
                'order' => 2,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 18,
                'caption' => 'សត្វមាន់',
		'slug' => 'សត្វមាន់',
                'parent_id' => 2,
		'article'  => 1,
                'market'  => 1,
		'real_estate' => 0,
		'job' => 0,
                'order' => 3,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 19,
                'caption' => 'សត្វ​ទា',
		'slug' => 'សត្វ​ទា',
                'parent_id' => 2,
		'article'  => 1,
                'market'  => 1,
		'real_estate' => 0,
		'job' => 0,
                'order' => 4,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 20,
                'caption' => 'សត្វក្រពើ',
		'slug' => 'សត្វក្រពើ',
                'parent_id' => 2,
		'article'  => 1,
                'market'  => 1,
		'real_estate' => 0,
		'job' => 0,
                'order' => 5,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 21,
                'caption' => 'សត្វអណ្ដើក',
		'slug' => 'សត្វអណ្ដើក',
                'parent_id' => 2,
		'article'  => 1,
                'market'  => 1,
		'real_estate' => 0,
		'job' => 0,
                'order' => 6,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 22,
                'caption' => 'ត្រី',
		'slug' => 'ត្រី',
                'parent_id' => 2,
		'article'  => 1,
                'market'  => 1,
		'real_estate' => 0,
		'job' => 0,
                'order' => 7,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            // Input company
            array(
                'id'    => 23,
                'caption' => 'ឧបករណ៍កសិកម្ម',
		'slug' => 'ឧបករណ៍កសិកម្ម',
                'parent_id' => 3,
                'article'  => 0,
                'market'  => 1,
		'real_estate' => 0,
		'job' => 0,
                'order' => 1,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 24,
                'caption' => 'ថ្នាំសំលាប់សត្វល្អិត',
		'slug' => 'ថ្នាំសំលាប់សត្វល្អិត',
                'parent_id' => 3,
                'article'  => 0,
                'market'  => 1,
		'real_estate' => 0,
		'job' => 0,
                'order' => 2,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 25,
                'caption' => 'ជី',
		'slug' => 'ជី',
                'parent_id' => 3,
                'article'  => 0,
                'market'  => 1,
		'real_estate' => 0,
		'job' => 0,
                'order' => 3,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 26,
                'caption' => 'គ្រាប់ពូជ',
		'slug' => 'គ្រាប់ពូជ',
                'parent_id' => 3,
                'article'  => 0,
                'market'  => 1,
		'real_estate' => 0,
		'job' => 0,
                'order' => 4,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 27,
                'caption' => 'ចំណីសត្វ',
		'slug' => 'ចំណីសត្វ',
                'parent_id' => 3,
                'article'  => 0,
                'market'  => 1,
		'real_estate' => 0,
		'job' => 0,
                'order' => 5,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 28,
                'caption' => 'វ៉ាក់សាំង',
		'slug' => 'វ៉ាក់សាំង',
                'parent_id' => 3,
                'article'  => 0,
                'market'  => 1,
		'real_estate' => 0,
		'job' => 0,
                'order' => 6,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            // Real Estate
            array(
                'id'    => 29,
                'caption' => 'ស្រែសម្រាប់​លក់',
		'slug' => 'ស្រែសម្រាប់​លក់',
                'parent_id' => 4,
                'article'  => 0,
                'market'  => 0,
		'real_estate' => 1,
		'job' => 0,
                'order' => 1,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 30,
                'caption' => 'ស្រែសម្រាប់​ជួល',
		'slug' => 'ស្រែសម្រាប់​ជួល',
                'parent_id' => 4,
                'article'  => 0,
                'market'  => 0,
		'real_estate' => 1,
		'job' => 0,
                'order' => 2,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 31,
                'caption' => 'ចំការសម្រាប់លក់',
		'slug' => 'ចំការសម្រាប់លក់',
                'parent_id' => 4,
                'article'  => 0,
                'market'  => 0,
		'real_estate' => 1,
		'job' => 0,
                'order' => 3,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 32,
                'caption' => 'ចំការសម្រាប់​ជួល',
		'slug' => 'ចំការសម្រាប់​ជួល',
                'parent_id' => 4,
                'article'  => 0,
                'market'  => 0,
		'real_estate' => 1,
		'job' => 0,
                'order' => 4,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 33,
                'caption' => 'កសិដ្ឋាន​សម្រាប់លក់',
		'slug' => 'កសិដ្ឋាន​សម្រាប់លក់',
                'parent_id' => 4,
                'article'  => 0,
                'market'  => 0,
		'real_estate' => 1,
		'job' => 0,
                'order' => 5,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 34,
                'caption' => 'កសិដ្ឋានសម្រាប់ជួល',
		'slug' => 'កសិដ្ឋានសម្រាប់ជួល',
                'parent_id' => 4,
                'article'  => 0,
                'market'  => 0,
		'real_estate' => 1,
		'job' => 0,
                'order' => 6,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            //Job
            array(
                'id'    => 35,
                'caption' => 'Accounting & Finance',
                'slug'  => 'accounting-finance',
                'parent_id' => 5,
                'article'  => 0,
                'market'  => 0,
		'real_estate' =>0,
		'job' => 1,
                'order' => 1,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 36,
                'caption' => 'Admin & Supervisory',
                'slug'  => 'admin-supervisory',
                'parent_id' => 5,
                'article'  => 0,
                'market'  => 0,
		'real_estate' =>0,
		'job' => 1,
                'order' => 2,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 37,
                'caption' => 'Advisory',
                'slug'  => 'advisory',
                'parent_id' => 5,
                'article'  => 0,
                'market'  => 0,
		'real_estate' =>0,
		'job' => 1,
                'order' => 3,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 38,
                'caption' => 'Advocacy',
                'slug'  => 'advocacy',
                'parent_id' => 5,
                'article'  => 0,
                'market'  => 0,
		'real_estate' =>0,
		'job' => 1,
                'order' => 4,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 39,
                'caption' => 'Agriculture',
                'slug'  => 'agriculture',
                'parent_id' => 5,
                'article'  => 0,
                'market'  => 0,
		'real_estate' =>0,
		'job' => 1,
                'order' => 5,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 40,
                'caption' => 'Analyst & Assessment',
                'slug'  => 'analyst-assessment',
                'parent_id' => 5,
                'article'  => 0,
                'market'  => 0,
		'real_estate' =>0,
		'job' => 1,
                'order' => 6,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 41,
                'caption' => 'Architecture',
                'slug'  => 'architecture',
                'parent_id' => 5,
                'article'  => 0,
                'market'  => 0,
		'real_estate' =>0,
		'job' => 1,
                'order' => 7,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 42,
                'caption' => 'Arts & Graphic Design',
                'slug'  => 'arts-graphic-design',
                'parent_id' => 5,
                'article'  => 0,
                'market'  => 0,
		'real_estate' =>0,
		'job' => 1,
                'order' => 8,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 43,
                'caption' => 'Assistant',
                'slug'  => 'assistant',
                'parent_id' => 5,
                'article'  => 0,
                'market'  => 0,
		'real_estate' =>0,
		'job' => 1,
                'order' => 9,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 44,
                'caption' => 'Business Administration',
                'slug'  => 'business-administration',
                'parent_id' => 5,
                'article'  => 0,
                'market'  => 0,
		'real_estate' =>0,
		'job' => 1,
                'order' => 10,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 45,
                'caption' => 'Call for Proposals',
                'slug'  => 'call-for-proposals',
                'parent_id' => 5,
                'article'  => 0,
                'market'  => 0,
		'real_estate' =>0,
		'job' => 1,
                'order' => 11,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 46,
                'caption' => 'Capacity Development',
                'slug'  => 'capacity-development',
                'parent_id' => 5,
                'article'  => 0,
                'market'  => 0,
		'real_estate' =>0,
		'job' => 1,
                'order' => 12,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 47,
                'caption' => 'Child Care',
                'slug'  => 'child-care',
                'parent_id' => 5,
                'article'  => 0,
                'market'  => 0,
		'real_estate' =>0,
		'job' => 1,
                'order' => 13,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 48,
                'caption' => 'Communications',
                'slug'  => 'communications',
                'parent_id' => 5,
                'article'  => 0,
                'market'  => 0,
		'real_estate' =>0,
		'job' => 1,
                'order' => 14,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 49,
                'caption' => 'Computer Networking',
                'slug'  => 'computer-networking',
                'parent_id' => 5,
                'article'  => 0,
                'market'  => 0,
		'real_estate' =>0,
		'job' => 1,
                'order' => 15,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 50,
                'caption' => 'Computer Programming',
                'slug'  => 'computer-programming',
                'parent_id' => 5,
                'article'  => 0,
                'market'  => 0,
		'real_estate' =>0,
		'job' => 1,
                'order' => 16,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 51,
                'caption' => 'Construction',
                'slug'  => 'construction',
                'parent_id' => 5,
                'article'  => 0,
                'market'  => 0,
		'real_estate' =>0,
		'job' => 1,
                'order' => 17,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 52,
                'caption' => 'Consultancy',
                'slug'  => 'consultancy',
                'parent_id' => 5,
                'article'  => 0,
                'market'  => 0,
		'real_estate' =>0,
		'job' => 1,
                'order' => 18,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 53,
                'caption' => 'Customer Service & Support',
                'slug'  => 'customer-service-Support',
                'parent_id' => 5,
                'article'  => 0,
                'market'  => 0,
		'real_estate' =>0,
		'job' => 1,
                'order' => 19,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 54,
                'caption' => 'Driving & Transport',
                'slug'  => 'driving-transport',
                'parent_id' => 5,
                'article'  => 0,
                'market'  => 0,
		'real_estate' =>0,
		'job' => 1,
                'order' => 20,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                 'id'    => 55,
                'caption' => 'Economics',
                'slug'  => 'economics',
                'parent_id' => 5,
                'article'  => 0,
                'market'  => 0,
		'real_estate' =>0,
		'job' => 1,
                'order' => 21,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),

            array(
                'id'    => 56,
                'caption' => 'Engineering',
                'slug'  => 'engineering',
                'parent_id' => 5,
                'article'  => 0,
                'market'  => 0,
		'real_estate' =>0,
		'job' => 1,
                'order' => 22,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 57,
                'caption' => 'Entertainment',
                'slug'  => 'entertainment',
                'parent_id' => 5,
                'article'  => 0,
                'market'  => 0,
		'real_estate' =>0,
		'job' => 1,
                'order' => 23,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 58,
                'caption' => 'Expression of Interest',
                'slug'  => 'expression-of-interest',
                'parent_id' => 5,
                'article'  => 0,
                'market'  => 0,
		'real_estate' =>0,
		'job' => 1,
                'order' => 24,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 59,
                'caption' => 'Fashion',
                'slug'  => 'fashion',
                'parent_id' => 5,
                'article'  => 0,
                'market'  => 0,
		'real_estate' =>0,
		'job' => 1,
                'order' => 25,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 60,
                'caption' => 'Freelancer',
                'slug'  => 'freelancer',
                'parent_id' => 5,
                'article'  => 0,
                'market'  => 0,
		'real_estate' =>0,
		'job' => 1,
                'order' => 26,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 61,
                'caption' => 'Health & Medical',
                'slug'  => 'health-medical',
                'parent_id' => 5,
                'article'  => 0,
                'market'  => 0,
		'real_estate' =>0,
		'job' => 1,
                'order' => 27,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 62,
                'caption' => 'Home Care & Labour',
                'slug'  => 'home-care-labour',
                'parent_id' => 5,
                'article'  => 0,
                'market'  => 0,
		'real_estate' =>0,
		'job' => 1,
                'order' => 28,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 63,
                'caption' => 'Hotel & Restaurant',
                'slug'  => 'hotel-restaurant',
                'parent_id' => 5,
                'article'  => 0,
                'market'  => 0,
		'real_estate' =>0,
		'job' => 1,
                'order' => 29,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 64,
                'caption' => 'HR',
                'slug'  => 'hr',
                'parent_id' => 5,
                'article'  => 0,
                'market'  => 0,
		'real_estate' =>0,
		'job' => 1,
                'order' => 30,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 65,
                'caption' => 'Import & Export',
                'slug'  => 'import-export',
                'parent_id' => 5,
                'article'  => 0,
                'market'  => 0,
		'real_estate' =>0,
		'job' => 1,
                'order' => 31,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 66,
                'caption' => 'Internship',
                'slug'  => 'internship',
                'parent_id' => 5,
                'article'  => 0,
                'market'  => 0,
		'real_estate' =>0,
		'job' => 1,
                'order' => 32,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 67,
                'caption' => 'Invitation for Bids',
                'slug'  => 'invitation-for-bids',
                'parent_id' => 5,
                'article'  => 0,
                'market'  => 0,
		'real_estate' =>0,
		'job' => 1,
                'order' => 33,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 68,
                'caption' => 'Law',
                'slug'  => 'law',
                'parent_id' => 5,
                'article'  => 0,
                'market'  => 0,
		'real_estate' =>0,
		'job' => 1,
                'order' => 34,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 69,
                'caption' => 'Management',
                'slug'  => 'management',
                'parent_id' => 5,
                'article'  => 0,
                'market'  => 0,
		'real_estate' =>0,
		'job' => 1,
                'order' => 35,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 70,
                'caption' => 'Manufacture & Operations',
                'slug'  => 'manufacture-operations',
                'parent_id' => 5,
                'article'  => 0,
                'market'  => 0,
		'real_estate' =>0,
		'job' => 1,
                'order' => 36,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 71,
                'caption' => 'Media',
                'slug'  => 'media',
                'parent_id' => 5,
                'article'  => 0,
                'market'  => 0,
		'real_estate' =>0,
		'job' => 1,
                'order' => 37,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 72,
                'caption' => 'Monitoring & Evaluation',
                'slug'  => 'monitoring-evaluation',
                'parent_id' => 5,
                'article'  => 0,
                'market'  => 0,
		'real_estate' =>0,
		'job' => 1,
                'order' => 38,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 73,
                'caption' => 'Research & Development',
                'slug'  => 'research-development',
                'parent_id' => 5,
                'article'  => 0,
                'market'  => 0,
		'real_estate' =>0,
		'job' => 1,
                'order' => 39,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 74,
                'caption' => 'Resources & Environment',
                'slug'  => 'resources-environment',
                'parent_id' => 5,
                'article'  => 0,
                'market'  => 0,
		'real_estate' =>0,
		'job' => 1,
                'order' => 40,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 75,
                'caption' => 'Rural Development',
                'slug'  => 'rural-development',
                'parent_id' => 5,
                'article'  => 0,
                'market'  => 0,
		'real_estate' =>0,
		'job' => 1,
                'order' => 41,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 76,
                'caption' => 'Sales & Marketing',
                'slug'  => 'sales-marketing',
                'parent_id' => 5,
                'article'  => 0,
                'market'  => 0,
		'real_estate' =>0,
		'job' => 1,
                'order' => 42,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 77,
                'caption' => 'Scholarships',
                'slug'  => 'scholarships',
                'parent_id' => 5,
                'article'  => 0,
                'market'  => 0,
		'real_estate' =>0,
		'job' => 1,
                'order' => 43,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 78,
                'caption' => 'Security',
                'slug'  => 'security',
                'parent_id' => 5,
                'article'  => 0,
                'market'  => 0,
		'real_estate' =>0,
		'job' => 1,
                'order' => 44,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 79,
                'caption' => 'Train & Teaching',
                'slug'  => 'train-teaching',
                'parent_id' => 5,
                'article'  => 0,
                'market'  => 0,
		'real_estate' =>0,
		'job' => 1,
                'order' => 45,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 80,
                'caption' => 'Translation & Interpretation',
                'slug'  => 'translation-interpretation',
                'parent_id' => 5,
                'article'  => 0,
                'market'  => 0,
		'real_estate' =>0,
		'job' => 1,
                'order' => 46,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 81,
                'caption' => 'Tourism',
                'slug'  => 'tourism',
                'parent_id' => 5,
                'article'  => 0,
                'market'  => 0,
		'real_estate' =>0,
		'job' => 1,
                'order' => 47,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 82,
                'caption' => 'Volunteer',
                'slug'  => 'volunteer',
                'parent_id' => 5,
                'article'  => 0,
                'market'  => 0,
		'real_estate' =>0,
		'job' => 1,
                'order' => 48,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 83,
                'caption' => 'Workshop',
                'slug'  => 'workshop',
                'parent_id' => 5,
                'article'  => 0,
                'market'  => 0,
		'real_estate' =>0,
		'job' => 1,
                'order' => 49,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            ),
            array(
                'id'    => 84,
                'caption' => 'Other',
                'slug'  => 'other',
                'parent_id' => 5,
                'article'  => 0,
                'market'  => 0,
		'real_estate' =>0,
		'job' => 1,
                'order' => 50,
		'status'=> 1,
                'created_at' => time(),
                'updated_at' => time()
            )
        );
        $this->db->insert_batch('category', $data);
    }

    public function down()
    {
        $this->dbforge->drop_table('category');
    }
}